app/views/beta/report_incident/reportv12/00timeout_complete.html
Tweak to timeout content so it's applicable to all roles
=> Tweak to timeout content

app/views/beta/_UR/20231121/b-interaction.html, app/views/beta/_UR/20231121/c-inappropriate.html, app/views/beta/_UR/20231121/c-why.html, app/views/beta/_UR/20231121/d-inappropriate.html, app/views/beta/_UR/20231121/d-inappropriate2.html, app/views/beta/_UR/20231121/index.html
Content tweaks for testing with users
=> Content tweaks for testing

app/views/beta/_UR/20231121/c-inappropriate.html
Content tweaks for UR testing in Nottingham JC
=> Content tweaks for UR testing

app/views/beta/_UR/20231121/d-inappropriate.html
Content tweak for UR testing in Nottingham JC
=> Content tweak for UR testing

app/views/beta/_UR/20231121/c-why.html
=> Content tweak for UR

app/views/beta/incident_manager_journey/v4/d02decision_notactive.html
Content update for https://dwpdigital.atlassian.net/browse/CITI-22251
=> Content update for CITI-22251

app/views/beta/incident_manager_journey/v4/d02decision_notactive.html
Content tweak for consistency (related to CITI-22251)
=> Content tweak for consistency

app/views/beta/decision/v7/h_04measures.html, app/views/beta/incident_manager_journey/v5/d02decision.html, app/views/beta/interaction/v2/01interaction.html
Content edits to measures: CITI-23385 CITI-23737 CITI-23738
=> Content edits to measures

app/views/beta/decision/v7/06measure.html, app/views/beta/decision/v7/07measureaccount.html, app/views/beta/decision/v7/09prepare_single_man.html, app/views/beta/decision/v7/11check_good.html
Content edits to measures: CITI-23735
=> Content edits to measures: CITI-23735

app/views/beta/decision/v7/06measure_error.html
Content tweak to errors to make consistent
=> Content tweak to errors to make consistent

app/views/beta/decision/v7/06measure_error.html
=> Content tweak to errors

app/views/beta/decision/v7/06measure_error.html
=> Content tweak to error

app/views/beta/common/landing/v4/templates/instructions.njk, app/views/beta/report_incident/reportv12/07where_location.html, app/views/beta/report_incident/reportv12/07where_location_error.html
Offline instructions and new location screen - content changes only
=> Offline instructions and new location screen - content changes only

app/views/beta/decision/v7/h07a_add.html, app/views/beta/decision/v7/h07a_add_error.html
Changes to content for CITI-21096
=> Changes to content for CITI-21096

app/views/beta/decision/v9/03gather.html
added waning message on gather page on decision v9
=> warning gather

app/views/beta/decision/v9/03gather_error.html, app/views/beta/decision/v9/03gather_success.html
Changed error page content and back button
made "gathering and assign to me" button disabled on gather success page
=> feedback from 3 amigos

app/assets/sass/application.scss, app/views/beta/interaction/v3/01interaction.html, package.json
fixing status tag and version update to match what's on dev's side
=> fixing status tag and version update

app/views/beta/report_incident/reportv12/c04check.html, app/views/beta/report_incident/reportv12/c04check_other.html, app/views/beta/report_incident/reportv12/c04check_unassigned.html
corrected it from "where this concern came from" to "This concern came from"
=> corrected the hiddentext

app/views/beta/decision/v8/02history_complex.html, app/views/beta/decision/v8/10incident_best_simple_info.html, app/views/beta/decision/v8/h_02incident_best_simple.html, app/views/beta/decision/v8/h_02incident_best_simple_existing.html, app/views/beta/decision/v8/h_02incident_best_simple_vo.html, app/views/beta/decision/v8/h_03concern_best.html, app/views/beta/decision/v8/h_04measures_none_notactive.html, app/views/beta/decision/v8/h_11review_action_commends.html
putting Review Action Comments on the pages
=> Review action commend

app/views/beta/incident_manager_journey/v5/01landingpage2_manager.html
put in <span class='govuk-visually-hidden'>Action</span> in all the action items
=> hidden text

app/views/beta/decision/v8/02history_complex_norac.html, app/views/beta/decision/v8/h_02incident_best_simple_norac.html, app/views/beta/decision/v8/h_03concern_best_norac.html
put in pages without review action commends for UR
=> no rac pages

app/views/beta/decision/v8/01landingpage1_btsready.html
=> hidden text for action

app/views/beta/decision/v9/h_02incident_best_migrated.html, app/views/beta/decision/v9/notes/h_02incident_best_simple__notes.njk
=> migrated case

app/views/beta/decision/v9/h_02incident_best_migrated.html
make further information as its own seperate section
=> further information

app/views/beta/decision/v8/h_03concern_best.html, app/views/beta/decision/v8/h_03concern_best_migrated.html
=> concern migrated
